---
title: "Material"
editor: source
---


These videos cover essential concepts of R programming that will be beneficial during the workshop Please take the time to view them at your convenience.

## Videos 
- Welcome to the "R for Research" series! In this video, we will dive into the fundamentals of R, a powerful programming language and environment widely used in research and data analysis.R provides comprehensive tools and packages for statistical analysis, data visualization, and data manipulation. Whether you're a biologist, social scientist, or any researcher looking to harness the power of data, this series will equip you with the necessary skills to leverage R for your research projects.! Check it out: {{< video https://youtu.be/dQhZjmw9BK0 title="R for Research || Fundamentals of R: Part 1" aspect-ratio="16x9" >}}

- In Part 2, we will continue our exploration of the fundamentals of R, building upon the knowledge gained in Part 1. This video will cover additional essential topics to further enhance your skills in using R for research and data analysis. Check it out: {{< video https://youtu.be/f4AK5aPhGf4 title="R for Research || Fundamentals of R: Part 2" aspect-ratio="16x9" >}}


## Cheatsheets

| **Module** | **Code** |**Labs/Exercises**  | **HW** | **Cheatsheets/Giide**|
|------------|------------|----------|--------------|-------------------|
|[00_Introduction](modules/00_Intro/Intro.html)|[Topic](/modules/Intro.Rmd)|[qmd]()|[Lab01]()|[Cheatsheet01](/modules/cheatsheets/Day-1.pdf)| 
|[01_Setup](/modules/01_Setup/R_and_RStudio_installation.html)|[Topic](/modules/R_and_RStudio_installation.Rmd)|[qmd]()|  [Lab01]()|[Cheatsheet01](/modules/cheatsheets/Day-1.pdf)| 
|[02_RStudio](/modules/02_RStudio/RStudio.html)|[Topic](/modules/RStudio.Rmd)|[qmd](/modules/02_RStudio/lab)|  [Lab01]()|[Cheatsheet01](/modules/cheatsheets/Day-1.pdf)| 
|[03_Reproducibility](/modules/03_Reproducibility/Reproducibility.html)|[Topic](/modules/Reproducibility.Rmd)|[qmd]()|  [Lab01]()|[Cheatsheet01](/modules/cheatsheets/Day-1.pdf)| 
|[04_Basic_R](/modules/04_Basic_R/Basic_R.html)|[Topic](/modules/Basic_R.Rmd)|[qmd](/modules/04_Basic_R/lab)|  [Lab01]()|[Cheatsheet01](/modules/cheatsheets/Day-2.pdf)| 
|[05_Data_Structures](/modules/05_Data_Structures/Data_Structures.html)|[Topic](/modules/Data_Classes.Rmd)|[qmd](/modules/05_Data_Structures/Data_Structures.html)|  [Lab01]()|[Cheatsheet01](/modules/cheatsheets/Day-3.pdf)| 
|[06_Intermediate_R](/modules//06_Intermediate_R/Intermediate_R.html)|[Topic](/modules/Functions/Functions/Rmd)|[qmd](/modules/06_Intermediate_R/Functions/lab)|  [Lab01]()|[Cheatsheet01](/modules/cheatsheets/Day-9.pdf)| 
|[07_Data_IO](/modules/07_Data_IO/Data_IO.html)|[Topic](/modules/07_Data_IO/Data_IO.html)|[qmd](/modules/07_Data_IO/lab)|  [Lab01]()|[Cheatsheet01](/modules/cheatsheets/Day-5.pdf)| 
|[08_Manipulating_Data_in_R](/modules/08_Manipulating_Data_in_R/Manipulating_Data_in_R.html)|[Topic](/modules/Manipulating_Data_in_R.Rmd)|[qmd](/modules/08_Manipulating_Data_in_R/lab)|  [Lab01]()|[Cheatsheet01](/modules/cheatsheets/Day-6.pdf)| 
|[09_Data_Cleaning](/modules/09_Data_Cleaning/Data_Cleaning.html)|[Topic](/modules/Data_Cleaning.Rmd)|[qmd](/modules/09_Data_Cleaning/lab)|  [Lab01]()|[Cheatsheet01](/modules/cheatsheets/Day-5.pdf)| 
|[10_Data_Summarization](/modules/10_Data_Summarization/Data_Summarization.htm)|[Topic](/modules/Data_Summarization.Rmd)|[qmd](/modules/10_Data_Summarization/Data_Summarization.html)|  [Lab01](/modules/HW/homework2.html)|[Cheatsheet01](/modules/cheatsheets/Day-8.pdf)| 
|[11_Intro_Data_Visualization](/modules/11_Intro_Data_Visualization/esquisse.html)|[Topic](/modules/ggplot2.Rmd)|[qmd](/modules/11_Intro_Data_Visualization/lab)|  [Lab01]()|[Cheatsheet01](/modules/cheatsheets/Day-7.pdf)| 
|[12_Descriptive_Statistics](/modules/12_Descriptive_Statistics/Statistics.html)|[Topic](/modules/Statistics.Rmd)|[qmd](/modules/12_Descriptive_Statistics/lab)|  [Lab01](/modules/HW/homework3.html)|[Cheatsheet01]()| 

