# Exploring Data

## Variable Examination
- `head()`, `tail()`: Shows the first few or last few rows of the dataset to get a glimpse of the data.
- The `dim()` function returns a numeric vector with two elements: the number of rows and the number of columns, respectively.
- `sample()` functions are useful for inspecting and sampling data in R.
- `View()`: Opens a spreadsheet-like viewer to interactively explore the dataset.
- `names()`, colnames(): Retrieves the variable or column names of the dataset.
- `nrow()`, ncol(): Returns the number of rows or columns in the dataset.
- `unique()`: Finds unique values within a variable.
- `table()`: Generates frequency counts for categorical variables.
- `sample_n()` and `sample_frac()` from dplyr package provide additional sampling capabilities for data frames.

## Structure and Summary
- `str()`: Displays the structure of the dataset, including variable names, data types, and dimensions.
- The `glimpse()` function is not part of the skimr package but rather from the dplyr package. It provides a compact overview of a dataset by displaying a few rows and columns, along with their data types.
- These functions help in understanding data structure, examining specific rows, and generating random subsets.
- `summary()`: Provides a summary of the dataset, including descriptive statistics for numeric variables and frequency counts for categorical variables.

## Missing Data Handling:
- `is.na()`: Identifies missing values in the dataset.
- `na.omit()`: Removes rows with missing values from the dataset.

## Data Exploration using `skimr`
- The skimr package in R provides a set of functions for generating compact and informative summary statistics of datasets. 
- It helps you quickly understand the structure and content of your data. 

```{r, eval=FALSE}
# using skimr 
library(skimr)
skim_report <- skim(data)
```






