# Subset Variables (Columns) 

## Subset Columns
- The `select()` verb from the dplyr package provides a flexible and intuitive approach to select columns in a dataframe. 
- It allows you to specify column names or patterns using a concise and readable syntax. 
- Syntax: `select(data, column1, column2, ...)`
- Arguments:
  - `data:` The dataframe or tibble from which you want to select columns.
  - `column1, column2,` ...: Names of the columns you want to select. You can provide column names directly as arguments.


## Matching Functions 
- `starts_with("pattern")`: Select variables that start with a specific pattern.
- `ends_with("pattern")`: Select variables that end with a specific pattern.
- `contains("pattern")`: Select variables that contain a specific pattern.
- `matches("regex")`: Select variables that match a regular expression pattern.

## Column Selection Techniques

```{r, eval=FALSE}
# Selecting specific columns "col1" and "col2"
selected_data <- select(data, col1, col2)

# Select columns that start with "var_" or end with "_value"
selected_data <- select(data, starts_with("var_"), ends_with("_value"))

# Select columns in a specific order
selected_data <- select(data, col2, col1, col3)

# Select all columns except "col1"
selected_data <- select(data, -col1)
```


